apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wa5ticl7k-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c030032be0.9t2g.p3.openshiftapps.com/rhtap/rhtap-qe:150decf666a9aa42e980ccdfa22cb6c0c43cca5a@sha256:9dad8d470dad63e67747e09a334efd07b6a4a5bd9e6ac6dface2aac4152cda50
          name: container-image
